# Read `.txt` files with pandas

Examples aligned with Datacyber skills (`ingest-pandas-normalize`): comma- or **semicolon-separated** text, optional encoding.

Set `DATA_PATH` to a file your kernel can read (host path or a path inside Docker if the notebook runs there).

In [2]:
from pathlib import Path

import pandas as pd

pd.__version__

'3.0.2'

In [5]:
path_2025_q3 = "../data-local/indec/mercado_laboral/EPH/2025/Q1/EPH_usu_1er_Trim_2025_txt/usu_hogar_T125.txt"
data_2025_q3 = pd.read_csv(path_2025_q3, sep=";", encoding="utf-8")
data_2025_q3.head()

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,REALIZADA,REGION,MAS_500,AGLOMERADO,PONDERA,IV1,...,VII2_1,VII2_2,VII2_3,VII2_4,V5_01,V21_02,V21_03,V22_02,V22_03,V2_01
0,TQRMNOQVSHKOLNCDEGGFB00858441,2025,1,1,1,42,S,10,526,1,...,98,0,0,0,2,2,2,1,2,2
1,TQSMNORTSHMOLTCDEGGFB00877605,2025,1,1,1,42,S,10,610,1,...,98,0,0,0,2,2,2,2,2,0
2,TQRMNOQQXHMMMLCDEGGFB00877606,2025,1,1,1,42,S,10,446,1,...,1,0,0,0,2,1,2,1,2,1
3,TQRMNOTTWHMMLOCDEFIAH00877819,2025,1,1,1,43,S,2,656,1,...,98,0,0,0,2,1,2,2,2,1
4,TQRMNORQQHLMKOCDEHIBB00853810,2025,1,2,1,40,N,22,132,1,...,98,0,0,0,2,2,2,2,2,0

In [7]:
path_2025_q2 = "../data-local/indec/mercado_laboral/EPH/2025/Q2/usu_hogar_T225.txt"
data_2025_q2 = pd.read_csv(path_2025_q2, sep=";", encoding="utf-8")
data_2025_q2.head()

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,REALIZADA,REGION,MAS_500,AGLOMERADO,PONDERA,IV1,...,VII2_1,VII2_2,VII2_3,VII2_4,V5_01,V21_02,V21_03,V22_02,V22_03,V2_01
0,TQRMNOPUSHMOLQCDEFLID00881764,2025,2,1,1,43,S,5,522,1,...,4,0,0,0,1,2,2,2,2,0
1,TQRMNOQRPHKOLTCDEFLID00881765,2025,2,1,1,43,S,5,346,1,...,1,0,0,0,2,2,2,2,2,0
2,TQRMNOSTUHMMKOCDEIGED00879108,2025,2,1,1,43,N,30,163,1,...,97,0,0,0,2,2,2,2,2,0
3,TQRMNOQWYHKMKNCDEIGED00857021,2025,2,1,1,43,N,30,104,1,...,3,0,0,0,2,2,2,2,2,0
4,TQRMNOPRTHMMKRCDEIGED00878749,2025,2,1,1,43,N,30,131,1,...,96,0,0,0,2,2,2,2,2,1

In [8]:
## data q1
path_2025_q1 = "../data-local/indec/mercado_laboral/EPH/2025/Q1/EPH_usu_1er_Trim_2025_txt/usu_hogar_T125.txt"
data_2025_q1 = pd.read_csv(path_2025_q1, sep=";", encoding="utf-8")
data_2025_q1.head()

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,REALIZADA,REGION,MAS_500,AGLOMERADO,PONDERA,IV1,...,VII2_1,VII2_2,VII2_3,VII2_4,V5_01,V21_02,V21_03,V22_02,V22_03,V2_01
0,TQRMNOQVSHKOLNCDEGGFB00858441,2025,1,1,1,42,S,10,526,1,...,98,0,0,0,2,2,2,1,2,2
1,TQSMNORTSHMOLTCDEGGFB00877605,2025,1,1,1,42,S,10,610,1,...,98,0,0,0,2,2,2,2,2,0
2,TQRMNOQQXHMMMLCDEGGFB00877606,2025,1,1,1,42,S,10,446,1,...,1,0,0,0,2,1,2,1,2,1
3,TQRMNOTTWHMMLOCDEFIAH00877819,2025,1,1,1,43,S,2,656,1,...,98,0,0,0,2,1,2,2,2,1
4,TQRMNORQQHLMKOCDEHIBB00853810,2025,1,2,1,40,N,22,132,1,...,98,0,0,0,2,2,2,2,2,0

In [9]:
## append all quarters
df_all = pd.concat([data_2025_q1, data_2025_q2, data_2025_q3])
df_all.head()

## save to csv
# df_all.to_csv("../data-local/indec/mercado_laboral/EPH/2025/EPH_usu_all_Trim_2025_txt/usu_hogar_T125.csv", index=False)

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,REALIZADA,REGION,MAS_500,AGLOMERADO,PONDERA,IV1,...,VII2_1,VII2_2,VII2_3,VII2_4,V5_01,V21_02,V21_03,V22_02,V22_03,V2_01
0,TQRMNOQVSHKOLNCDEGGFB00858441,2025,1,1,1,42,S,10,526,1,...,98,0,0,0,2,2,2,1,2,2
1,TQSMNORTSHMOLTCDEGGFB00877605,2025,1,1,1,42,S,10,610,1,...,98,0,0,0,2,2,2,2,2,0
2,TQRMNOQQXHMMMLCDEGGFB00877606,2025,1,1,1,42,S,10,446,1,...,1,0,0,0,2,1,2,1,2,1
3,TQRMNOTTWHMMLOCDEFIAH00877819,2025,1,1,1,43,S,2,656,1,...,98,0,0,0,2,1,2,2,2,1
4,TQRMNORQQHLMKOCDEHIBB00853810,2025,1,2,1,40,N,22,132,1,...,98,0,0,0,2,2,2,2,2,0

In [12]:
path_2024_q3 = "../data-local/indec/mercado_laboral/EPH/2024/Q3/EPH_usu_3_Trim_2024_txt/usu_hogar_T324.txt"
data_2024_q3 = pd.read_csv(path_2024_q3, sep=";", encoding="utf-8")
data_2024_q3.head()

## data q2

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,REALIZADA,REGION,MAS_500,AGLOMERADO,PONDERA,IV1,...,VII2_1,VII2_2,VII2_3,VII2_4,V5_01,V21_02,V21_03,V22_02,V22_03,V2_01
0,TQSMNORUWHMNLNCDEGGFB00809685,2024,3,1,1,42,S,10,717,1,...,97,0,0,0,2,2,2,2,2,0
1,TQRMNORQSHMMKQCDEHMHF00811296,2024,3,1,1,42,N,26,143,1,...,98,0,0,0,2,2,2,2,2,1
2,TQRMNOPQTHMLNUCDEIIAD00812026,2024,3,1,1,1,S,32,249,2,...,98,0,0,0,2,2,2,2,2,0
3,TQSMNOQXUHMOLRCDEIJAH00812539,2024,3,1,1,1,S,33,1887,1,...,98,0,0,0,1,2,2,2,2,0
4,TQRMNOPPQHMMKRCDEGOIH00810573,2024,3,1,1,40,N,18,559,1,...,98,0,0,0,2,2,2,2,2,0